import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import Provider from "@/components/Provider";
import { auth } from "@/lib/auth";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "300", "500", "800", "700", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={openSans.className}
        // disable color zila listener
        cz-shortcut-listen="false"
      >
        <Provider session={session}>{children}</Provider>
      </body>
    </html>
  );
}
